apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: app
        image: mrrobotthecoder/jenkins-demo:IMAGE_TAG
        ports:
        - containerPort: 80
