apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
  namespace: demo
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
